"""add performance reviewstable

Revision ID: 0e0c488b5cdb
Revises: a5598d439e81
Create Date: 2026-07-23 10:04:42.488347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0c488b5cdb'
down_revision = 'a5598d439e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', name='reviewstatus'), nullable=False),
    sa.Column('overall_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_reviews_employee_id'), ['employee_id'], unique=False)

    op.create_table('performance_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'NOT_MET', name='goalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['performance_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_goals_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_goals_review_id'), ['review_id'], unique=False)

    op.create_table('review_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['performance_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_ratings_review_id'), ['review_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_ratings_review_id'))

    op.drop_table('review_ratings')
    with op.batch_alter_table('performance_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_goals_review_id'))
        batch_op.drop_index(batch_op.f('ix_performance_goals_employee_id'))

    op.drop_table('performance_goals')
    with op.batch_alter_table('performance_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_reviews_employee_id'))

    op.drop_table('performance_reviews')
    # ### end Alembic commands ###
