"""add scheduled_shifts table

Revision ID: 746c330d046a
Revises: 0e0c488b5cdb
Create Date: 2026-07-23 11:06:38.885914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746c330d046a'
down_revision = '0e0c488b5cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.Enum('OPENING', 'CLOSING', name='shifttype'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_employee_schedule_date')
    )
    with op.batch_alter_table('scheduled_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_shifts_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_shifts_employee_id'))

    op.drop_table('scheduled_shifts')
    # ### end Alembic commands ###
