"""add employee rest_day and weekly_shift_assignments

Revision ID: 788a7835d775
Revises: c52902d96e41
Create Date: 2026-07-23 16:17:16.378375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as pg_ENUM


# revision identifiers, used by Alembic.
revision = '788a7835d775'
down_revision = 'c52902d96e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('shift_type', pg_ENUM('OPENING', 'CLOSING', name='shifttype', create_type=False), nullable=False),
    sa.Column('rest_day', sa.Integer(), nullable=False),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'week_start_date', name='uq_employee_week')
    )
    with op.batch_alter_table('weekly_shift_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_shift_assignments_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rest_day', sa.Integer(), nullable=False, server_default=sa.text('6')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('rest_day')

    with op.batch_alter_table('weekly_shift_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_shift_assignments_employee_id'))

    op.drop_table('weekly_shift_assignments')
    # ### end Alembic commands ###
