"""add employee_documents table

Revision ID: a5598d439e81
Revises: f3e10a571f27
Create Date: 2026-07-22 17:38:52.181234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5598d439e81'
down_revision = 'f3e10a571f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('GOVERNMENT_ID', 'CONTRACT', 'CERTIFICATION', 'RESUME', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=500), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_documents_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_documents_employee_id'))

    op.drop_table('employee_documents')
    # ### end Alembic commands ###
