"""add employee biometric-id

Revision ID: c52902d96e41
Revises: 746c330d046a
Create Date: 2026-07-23 12:16:46.702603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52902d96e41'
down_revision = '746c330d046a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biometric_id', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['biometric_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('biometric_id')

    # ### end Alembic commands ###
